---
apiVersion: v1
kind: Secret
metadata:
  name: {{include "tdengine.fullname" .}}
  labels:
    {{- include "tdengine.labels" . | nindent 4 }}
data:
  root_user: {{ .Values.extraSecrets.root_user | default "" | b64enc | quote }}
  root_password: {{ .Values.extraSecrets.root_password | default "" | b64enc | quote }}
  sql_query: {{ .Values.extraSecrets.sql_query | default "" | b64enc | quote }}
