---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{include "component.name" .}}
  namespace: {{.Release.Namespace}}
spec:
  kafka:
    version: {{ .Values.kafka_version }}
    replicas: {{.Values.kafka_replicas}}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: tlsintern
        port: 9095
        type: internal
        tls: true
        authentication:
          type: tls
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
      - id: 1
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      default.replication.factor: 2
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
    authorization:
      type: simple
      superUsers:
        - CN=super-user
  zookeeper:
    replicas: {{.Values.zookeeper_replicas}}
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  cruiseControl: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}
